<?php

namespace App\Http\Resources\Form;

use Illuminate\Http\Resources\Json\JsonResource;

class FormItem extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
//        return parent::toArray($request);

        return [
            'id' => $this->id,
            'title' => $this->title,
            'option_count' => sizeof($this->options),
            'edit_link' => route('form.memorize.edit', $this->hash_id),
            'creator_name' => $this->creator_name,
            'creation_date' => $this->creation_date,
        ];
    }
    public function with($request): array
    {
//        return parent::with($request); // TODO: Change the autogenerated stub
        return [
          'version' => '1.0.0'
        ];
    }
}
